### ISSUE TITLE
ReDoc broken sidebar in Chrome 80

### ISSUE THREAD

**Issue by aklim007** [axnsan12/drf-yasg#548] opened 2020-02-17 11:37 UTC
This fixed in version 2.0.0-rc.23 ReDoc
https://github.com/Redocly/redoc/issues/1167

**Comment by hnykda** [comment] 2020-02-25 09:10
Is there a way how to use the fixed version via drf-yasg?

**Comment by danilocastelhano1** [comment] 2020-03-03 20:28
I have the same problem too, i'm using the version of drf-yasg: 1.17.1 and still happens

**Comment by danilocastelhano1** [comment] 2020-03-03 21:08
> Is there a way how to use the fixed version via drf-yasg?

I fixed the bug: go to your html page and change this:
<script src="{% static 'drf-yasg/redoc/redoc.min.js' %}"></script>
to this:
<script src="https://rebilly.github.io/ReDoc/releases/latest/redoc.min.js"></script>

**Comment by glebpushkov** [comment] 2020-03-27 16:14
As I see there is unmerged pr for this issue https://github.com/axnsan12/drf-yasg/pull/543

A bit elaborated solution above to fix my case when redoc is hosted somewhere:
1. Create new app, let's say - 'drf_yasg_templates'
2. Copy ...drf_yasg/templates/drf-yasg/redoc.html to the new app - drf_yasg_templates/templates/drf-yasg/redoc.html and replace 
`<script src="{% static 'drf-yasg/redoc/redoc.min.js' %}"></script>`
with 
`<script src="https://cdn.jsdelivr.net/npm/redoc@2.0.0-rc.23/bundles/redoc.standalone.js"></script>`
3. Add it to installed apps before 'drf_yasg'

**Comment by TauPan** [comment] 2020-04-14 13:52
Since the fix for https://github.com/Redocly/redoc/issues/1167 is in https://github.com/Redocly/redoc/commit/1a2a7dd8331cedd6ced4c18accf0b417549b3ff3
it should be sufficient to add/inject 

```css
.menu-content {
    contain: unset !important;
}

Into your application somehow.

**Comment by ingbunga** [comment] 2020-09-04 14:34
In my case,
The problem is solved by putting the latest redoc.min.js file in the Django static folder.

**Comment by axnsan12** [comment] 2020-10-25 17:28
Fixed in master now, updated to rc40, sorry for disappearing.

**Closed by axnsan12** 2020-10-25 17:28 UTC
