### ISSUE TITLE
Repeated url patterns results in failed validation

### ISSUE THREAD

**Issue by nikkelj** [axnsan12/drf-yasg#236] opened 2018-10-23 23:25 UTC
Validation fails if I supply two url patterns for the same endpoint, like so:
    url(r'^preferences/(?P\<username\>.+)$', views.preferences, name='preferences'),  
    url(r'^preferences', views.preferences, name='preferences'), 

It appears the ssv validator is the culprit.

Stack trace:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../.venv/django/lib/python3.5/site-packages/django/test/client.py:527: in get
    response = super().get(path, data=data, secure=secure, **extra)
../../.venv/django/lib/python3.5/site-packages/django/test/client.py:339: in get
    **extra,
../../.venv/django/lib/python3.5/site-packages/django/test/client.py:414: in generic
    return self.request(**r)
../../.venv/django/lib/python3.5/site-packages/django/test/client.py:495: in request
    raise exc_value
../../.venv/django/lib/python3.5/site-packages/django/core/handlers/exception.py:34: in inner
    response = get_response(request)
../../.venv/django/lib/python3.5/site-packages/django/core/handlers/base.py:156: in _get_response
    response = self.process_exception_by_middleware(e, request)
../../.venv/django/lib/python3.5/site-packages/django/core/handlers/base.py:154: in _get_response
    response = response.render()
../../.venv/django/lib/python3.5/site-packages/django/template/response.py:106: in render
    self.content = self.rendered_content
../../.venv/django/lib/python3.5/site-packages/rest_framework/response.py:72: in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
../../.venv/django/lib/python3.5/site-packages/drf_yasg/renderers.py:34: in render
    return codec.encode(data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <drf_yasg.codecs.OpenAPICodecJson object at 0x7f0965a36b00>
document = Swagger([('swagger', '2.0'), ('info', Info([('title', 'nav-services-gui'), ('version', '1.0.0')])), ('host', 'testserv..., Response([('description', '')]))])), ('tags', ['uaa'])])), ('parameters', [])]))])), ('definitions', OrderedDict())])

    def encode(self, document):
        """Transform an :class:`.Swagger` object to a sequence of bytes.
    
            Also performs validation and applies settings.
    
            :param openapi.Swagger document: Swagger spec object as generated by :class:`.OpenAPISchemaGenerator`
            :return: binary encoding of ``document``
            :rtype: bytes
            """
        if not isinstance(document, openapi.Swagger):
            raise TypeError('Expected a `openapi.Swagger` instance')
    
        spec = self.generate_swagger_object(document)
        errors = {}
        for validator in self.validators:
            try:
                # validate a deepcopy of the spec to prevent the validator from messing with it
                # for example, swagger_spec_validator adds an x-scope property to all references
                VALIDATORS[validator](copy.deepcopy(spec))
            except SwaggerValidationError as e:
                errors[validator] = str(e)
    
        if errors:
>           raise SwaggerValidationError("spec validation failed", errors, spec, self)
E           drf_yasg.errors.SwaggerValidationError: spec validation failed

../../.venv/django/lib/python3.5/site-packages/drf_yasg/codecs.py:73: SwaggerValidationError

Any thoughts?

**Comment by axnsan12** [comment] 2018-10-23 23:46
Are you sure that the error rises from the duplicate view? The exact details of the validation exception would be helpful...

**Comment by nikkelj** [comment] 2018-10-24 00:01
Positive, goes away when I remove the second url pattern.  I would get them for you but I am not sure how to dig them out tbh.

**Comment by nikkelj** [comment] 2018-10-24 00:02
Also goes away if I remove ssv validator and only use flex validator

**Comment by axnsan12** [comment] 2018-11-28 22:34
I can't reproduce this with the example you gave.

```python
    url(r'^plain/$', plain_view, name='preferences'),
    url(r'^plain/(?P<username>.+)$', plain_view, name='preferences'),
```

Works just fine: 

![image](https://user-images.githubusercontent.com/6382979/49186899-851ca800-f36e-11e8-8c6c-3da0c64e7b61.png)

**Comment by axnsan12** [comment] 2018-12-20 23:42
Going to close this as a heisenbug. Please reopen if you can provide more info.

**Closed by axnsan12** 2018-12-20 23:42 UTC
Labels: bug, more info needed

**Comment by geekashu** [comment] 2019-07-03 16:52
This is happening to me as well. I am using the latest version.

This is how my `urls.py` code looks. Here, I have delete method in both the Views.
```
urlpatterns = [
    path('country/', views.CountryList.as_view(), name='country-list'),
    path('country/<int:pk>/', views.CountryDetail.as_view(), name='country-detail'),
]
```

 In `CountyList` it is for bulk delete.
```
class CountryList(generics.ListCreateAPIView):
    queryset = Country.objects.all()
    pagination_class = BasicPagination
    filter_backends = (SearchFilter, OrderingFilter)
    search_fields = ('name', 'capital', 'iso_code_2')
    ordering_fields = search_fields

    def get_serializer_class(self):
        if self.request.method == 'POST':
            return CountrySerializer
        return CountryListSerializer

    def post(self, request, *args, **kwargs):
        return super(CountryList, self).post(request, *args, **kwargs)

    # This is for bulk delete.
    def delete(self, request, *args, **kwargs):
        if "by" in request.query_params:
            qs = self.get_queryset()
            filter_string = request.query_params["by"] + "__in"
            filtered = qs.filter(**{filter_string: request.data})
            if not filtered:
                return Response(status=status.HTTP_400_BAD_REQUEST)
            [obj.delete() for obj in filtered]

            return Response(status=status.HTTP_204_NO_CONTENT)
        return Response(status=status.HTTP_400_BAD_REQUEST)
```

This is my CountryDetail.
```
class CountryDetail(generics.RetrieveUpdateDestroyAPIView):
    serializer_class = CountrySerializer
```

This is the error I am getting. Though all my test cases are passing perfectly. I don't have any issue in API access.
`drf_yasg.errors.SwaggerValidationError: spec validation failed: {'ssv': 'Duplicate operationId: country_delete'}`

Can we do a little more investigation on this?

**Comment by axnsan12** [comment] 2019-07-03 17:47
Set the operation_id of one of the endpoints manually to avoid the problem.

**Comment by geekashu** [comment] 2019-07-03 19:20
Thanks for the quick reply. I didn't get you. How do I put the `operation_id` for one endpoint? In the urlpatterns?

**Comment by axnsan12** [comment] 2019-07-03 19:33
You can use the @swagger_auto_schema directly on the view method.

**Comment by axnsan12** [comment] 2019-07-03 19:33
You can use the `@swagger_auto_schema` decorator directly on the view method.

**Comment by geekashu** [comment] 2019-07-03 19:38
Ah!. It worked. Thanks a ton.
