### ISSUE TITLE
Filter is not propagated to swagger

### ISSUE THREAD

**Issue by NN---** [axnsan12/drf-yasg#192] opened 2018-08-29 13:11 UTC
Schema generated by Django: http://www.django-rest-framework.org/topics/3.5-announcement/
produces correctly a REST method with filter.
Swagger created using this library doesn't do this.

Field 'abc' is appeared in both , but 'id' doesn't appear in swagger openapi.

```py
class SomeFilterWithId(django_filters.FilterSet):
    class Meta:
        model = SomeModel
        fields = ["abc","id"]
```

**Comment by axnsan12** [comment] 2018-09-09 21:08
This will need a more complete explanation/reproduction. Generally, filters should work the same between the two generators because the related code of ``django-rest-framework`` is reused by ``drf-yasg``.

**Comment by axnsan12** [comment] 2018-12-11 18:23
I'm closing this for lack of information. Please reopen if you have anything to add.

**Closed by axnsan12** 2018-12-11 18:23 UTC
Labels: more info needed
