### ISSUE TITLE
Current DRF-YASG version is not compatible with drf latest version 3.14.0

### ISSUE THREAD

**Issue by prakharrathi25** [axnsan12/drf-yasg#812] opened 2022-09-23 07:24 UTC
# Bug Report

## Description

I have been facing an issue with `drf-yasg==1.23.1` after the release of latest `djangorestframework==3.14.0`. They have removed the support for `NullBooleanField` in the latest version of `rest_framework.serializers`. Please update the drf-yasg version accordingly since this is a breaking change. 

## Is this a regression?

No, it's caused by django_rest_framework version 3.14.0. 

## Minimal Reproduction

```code
from drf_yasg.generators import OpenAPISchemaGenerator 
```
in any django app. 

## Stack trace / Error message

```code
File "/home/runner/work/Shoonya-Backend/Shoonya-Backend/backend/shoonya_backend/urls.py", line 8, in <module>
    from drf_yasg.generators import OpenAPISchemaGenerator
  File "/opt/hostedtoolcache/Python/3.8.13/x[64](https://github.com/AI4Bharat/Shoonya-Backend/actions/runs/3110830209/jobs/5042426356#step:6:65)/lib/python3.8/site-packages/drf_yasg/generators.py", line 19, in <module>
    from .inspectors.field import get_basic_type_info, get_queryset_field, get_queryset_from_view
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/drf_yasg/inspectors/__init__.py", line 5, in <module>
    from .field import (
  File "/opt/hostedtoolcache/Python/3.8.13/x64/lib/python3.8/site-packages/drf_yasg/inspectors/field.py", line 406, in <module>
    (serializers.NullBooleanField, (openapi.TYPE_BOOLEAN, None)),
AttributeError: module 'rest_framework.serializers' has no attribute 'NullBooleanField'
```

More details can be found here - https://github.com/AI4Bharat/Shoonya-Backend/actions/runs/3110830209/jobs/5042426356

## Your Environment
This is failing in pytest.

**Comment by yamac-kurtulus** [comment] 2022-09-23 11:06
see #810, For now I am using an older version of DRF (3.12) And there is a PR for this, albeit it would drop support for DRF < 3.14

**Comment by JoelLefkowitz** [comment] 2022-09-24 10:27
Closing as a duplicate of #810.

**Closed by JoelLefkowitz** 2022-09-24 10:27 UTC
