### ISSUE TITLE
Assertion error when trying to visit the page

### ISSUE THREAD

**Issue by nicholasgcoles** [axnsan12/drf-yasg#59] opened 2018-02-15 15:09 UTC
Hello

Thanks for the great project! I am trying to get it working with my current setup but am running into the following error
```
AssertionError at /redoc/
#/definitions/Nested already exists
```
I think the error has got something to do with how I have defined my ViewSets because it goes away when I remove some of my viewsets from the ```router.register()``` option in urls.py

I hope I have explained this well enough?

**Comment by axnsan12** [comment] 2018-02-15 15:16
Hello!

You probably have multiple serializers named NestedSerializer in different packages. Each serializer gets mapped to an OpenAPI named model according to its name. You could go to each serializer in question and explicitly [give it a more distinctive name](http://drf-yasg.readthedocs.io/en/stable/custom_spec.html#serializer-meta-nested-class), or force it to be generated as an inline model (both will work if you only care about the documentation aspect).

**Comment by nicholasgcoles** [comment] 2018-02-15 18:35
Hey thanks for the quick reply!

None of the serializers I am using have a nested serializer called "NestedSerializer". One of my serializers which aren't working looks like this:

```
class ClientSerializer(serializers.ModelSerializer):
    """
    Serializer for clients
    """
    items = ItemSerializer(many=True, read_only=True)

    class Meta:
        model = Client
        fields = ('id', 'user', 'items', 'company')
```

Is there something I am doing wrong? I tried to look at that documentation but I was unsure as what to do with the "ref_name" attribute?

Thanks again!

**Comment by axnsan12** [comment] 2018-02-15 18:39
Huh. If that is the case then this might be a bug.

For the ``ref_name`` attribute, you would add it to the serializer ``Meta`` class.

**Comment by nicholasgcoles** [comment] 2018-02-15 18:58
Hey! I realise I had ```depth=3``` in one of the serializers which seemed to cause an issue.

I set the ```depth=1``` and that has fixed the problem and going to debug further on my side. 

Thanks so much for the help!

**Comment by axnsan12** [comment] 2018-02-15 19:00
That shouldn't be a problem, or if it is, it should be fixed. So please do report if you find that it is a bug caused by this library.

**Comment by dilipMaharjan** [comment] 2018-02-16 15:38
I just confirmed that if depth is greater than 1, it throws the mentioned error.

**Comment by axnsan12** [comment] 2018-02-16 18:41
Ok, I'll try to figure it out. Any code example (e.g. ``django-admin startproject`` with minimal changes) that shows the problem would be of great help, if it's not too hard!

**Comment by dilipMaharjan** [comment] 2018-02-19 14:51
I tried to reproduce the error this morning but couldn't which means its probably the way models are related, if I will have time, I will try it again some time later.

**Comment by dilipMaharjan** [comment] 2018-02-21 21:34
@axnsan12  This a example project to view the issue https://github.com/dilipMaharjan/drf_yasg_depth_issue

Steps:
1. Clone the project
2. Run docker-compose up
3. In your browser, type localhost/docs/
4.Change the depth to 1 in CSerializer and it works
I hope this helps.

**Comment by axnsan12** [comment] 2018-02-22 00:26
Hello!

Thanks a lot for the example app, it's great! The problem seems to be caused by having ``ModelSerializer``s with [implicitly generated ``NestedSerializer``](https://github.com/encode/django-rest-framework/blob/d2994e0596c3163ac970b29dad6a61485f938045/rest_framework/serializers.py#L1240)s for their model's ``ForeignKey`` relations...

It can be worked around by defining nested fields explicitly on your ``ModelSerializer`` to indicate which serializer they should use. 

The permanent fix will likely be to force all such automatic serializers to be output inline (e.g. no entry in the bottom ``Models`` section, no sub-model name when viewing the operation). If you want to keep the named/by-reference behaviour you will have to implement the solution mentioned above anyway.

**Closed** 2018-02-22 01:46 UTC
Labels: bug

**Comment by dilipMaharjan** [comment] 2018-02-22 13:59
Thanks.
