### ISSUE TITLE
[Help Needed] 500 Error when visiting API doc

### ISSUE THREAD

**Issue by Saad-K** [axnsan12/drf-yasg#248] opened 2018-11-06 16:24 UTC
Hi,

I am getting an error when visiting the swagger api site, I have looked at the existing and old issues, searched around the internets but couldn't find an answer. I have also looked at the server logs, but I feel like I am missing something very obvious.
```
Failed to load API
Fetch errorInternal Server Error http://localhost/docs/?format=openapi
```
In my server logs I get the following message 
```
Internal Server Error: /swagger/
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  |     response = get_response(request)
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
  |     response = self.process_exception_by_middleware(e, request)
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
  |     response = response.render()
  |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 106, in render
  |     self.content = self.rendered_content
  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
  |     ret = renderer.render(self.data, accepted_media_type, context)
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/renderers.py", line 34, in render
  |     return codec.encode(data)
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 74, in encode
  |     return force_bytes(self._dump_dict(spec))
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 104, in _dump_dict
  |     return json.dumps(spec)
  |   File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
  |     return _default_encoder.encode(obj)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
  |     chunks = self.iterencode(o, _one_shot=True)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
  |     return _iterencode(o, 0)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
  |     o.__class__.__name__)
  | TypeError: Object of type 'Africa/Abidjan' is not JSON serializable
  | [2018-11-06 16:08:03] ERROR Internal Server Error: /swagger/
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
  |     response = get_response(request)
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
  |     response = self.process_exception_by_middleware(e, request)
  |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 154, in _get_response
  |     response = response.render()
  |   File "/usr/local/lib/python3.6/site-packages/django/template/response.py", line 106, in render
  |     self.content = self.rendered_content
  |   File "/usr/local/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
  |     ret = renderer.render(self.data, accepted_media_type, context)
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/renderers.py", line 34, in render
  |     return codec.encode(data)
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 74, in encode
  |     return force_bytes(self._dump_dict(spec))
  |   File "/usr/local/lib/python3.6/site-packages/drf_yasg/codecs.py", line 104, in _dump_dict
  |     return json.dumps(spec)
  |   File "/usr/local/lib/python3.6/json/__init__.py", line 231, in dumps
  |     return _default_encoder.encode(obj)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
  |     chunks = self.iterencode(o, _one_shot=True)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
  |     return _iterencode(o, 0)
  |   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
  |     o.__class__.__name__)
  | TypeError: Object of type 'Africa/Abidjan' is not JSON serializable
```
This is my `urls.py` file
```
if settings.DEBUG:
    from drf_yasg.views import get_schema_view
    from drf_yasg import openapi
    from rest_framework import permissions

    schema_view = get_schema_view(
        openapi.Info(
            title="test API",
            default_version="v1",
            description="test",
            contact=openapi.Contact(email="test@gmail.com"),
            schemes=["http", "https"],
        ),
        # validators=[],
        public=False,
        permission_classes=(permissions.IsAuthenticated,),
    )

    urlpatterns += [
        re_path(
            r"^swagger(?P<format>\.json|\.yaml)$",
            schema_view.without_ui(cache_timeout=0),
            name="schema-json",
        ),
        re_path(
            r"^swagger/$",
            schema_view.with_ui("swagger", cache_timeout=0),
            name="schema-swagger-ui",
        ),
        re_path(
            r"^redoc/$",
            schema_view.with_ui("redoc", cache_timeout=0),
            name="schema-redoc",
        ),
    ]
```
I have no clue where the type error is coming from, I havent specified `Africa/Abidjan` anywhere in my Django drf code.

P.S I love the this module and the clean UI

**Comment by vishes-shell** [comment] 2018-11-06 16:29
@Saad-K i suggest you eliminate url namespace by namespace, until you find what causing you trouble, after namespace is found, you can start eliminating urls. After such procedures you will know what view is causing you trouble. If you won't be able to deal with your error by yourself, post _view_ code, and we will try figure out what causing you problem.

**Comment by axnsan12** [comment] 2018-11-07 11:02
I second the above message.

This looks like a bug triggered by some third party model/serializer field, probably has to do with string handling. Judging from the name in the message, might be some timezone-related enum.

**Comment by Saad-K** [comment] 2018-11-07 14:54
Also I forgot to mention that everything runs fine with the exact same setup if I use 
drf-yasg==1.9.1
django==2.0.7
djangorestframework==3.8.2

Its the latest version of django that causes the issue.
Thanks guys, I will remove the namespace and check the error again.

**Comment by axnsan12** [comment] 2018-11-12 23:13
Any info on this? Did you manage to pinpoint the field causing the issue?

**Comment by XUANLANcognition** [comment] 2018-11-27 03:51
I am having the same problem. And I found out it was because : 
`"No module named 'flex'"`

So, I'm deleting `validators=['flex',` `'ssv']`(in url.py) at the moment to be successful.

**Comment by Saad-K** [comment] 2018-11-27 16:34
I have found the offending code, by the process of elimination. I commented out the urls to see which one is not working, I removed the namespace but that didn't work. It seems to be coming from django [celery beat module](https://github.com/celery/django-celery-beat/tree/master/django_celery_beat)

```
- urls.py
router = routers.SimpleRouter()
router.register(r"crontab-schedules", views.CrontabScheduleViewset)
```

```
- serializers.py
class CrontabScheduleSerializer(serializers.ModelSerializer):
    class Meta:
        model = CrontabSchedule
        fields = "__all__"
```
```
- views.py
class CrontabScheduleViewset(mixins.CreateModelMixin,
                                                      mixins.ListModelMixin,
                                                      mixins.RetrieveModelMixin,
                                                      mixins.UpdateModelMixin,
                                                      mixins.DestroyModelMixin,
                                                      viewsets.GenericViewSet):
    queryset = CrontabSchedule.objects.all()
    serializer_class = CrontabScheduleSerializer
```

I am using other models from django-celery-beat, for e.g PeriodicTask in exactly the same manner but this is the only one thats is causing this issue.

**Comment by axnsan12** [comment] 2018-11-28 23:10
Hey, so I looked into this and the behaviour here seems correct. The serializer you posted won't even work in a real view, failing with the same error. 

The problem is that the model field returns ``pytz.BaseTzInfo`` objects, which, as the error says, cannot be directly serialized to JSON. Something like below should work.

```python
class TimeZoneField(serializers.ChoiceField):
    def __init__(self, **kwargs):
        kwargs.setdefault('choices', timezone_field.TimeZoneField.CHOICES)
        super(TimeZoneField, self).__init__(**kwargs)

    def to_representation(self, value):
        return six.text_type(value)

class CrontabScheduleSerializer(serializers.ModelSerializer):
    timezone = TimeZoneField()
```

**Comment by axnsan12** [comment] 2018-12-20 23:43
Going to close this as resolved/not applicable. Please reopen if you can provide more info.

**Closed by axnsan12** 2018-12-20 23:43 UTC
Labels: bug, more info needed

**Comment by cs-satish-mishra** [comment] 2020-11-02 11:25
@Saad-K  could you find any solution to this, I am also facing exactly the same issue due to the celery beat module?
