### ISSUE TITLE
Redoc will never display in urls correctly

### ISSUE THREAD

**Issue by sultansgillani** [axnsan12/drf-yasg#157] opened 2018-07-03 19:03 UTC
Ever since I have installed drf-yasg (Almost 6 months ago), I cannot seem to get redoc to work correctly.

Here is the normal error I get: 
```
"http://127.0.0.1:8000/api/v1/redoc/?format=openapi" is not a valid JSON Schema
Stack trace
SyntaxError: "http://127.0.0.1:8000/api/v1/redoc/?format=openapi" is not a valid JSON Schema
    at Function.syntax (http://127.0.0.1:8000/static/drf-yasg/redoc/redoc.min.js:55:18937)
    at http://127.0.0.1:8000/static/drf-yasg/redoc/redoc.min.js:73:51233

ReDoc Version: 2.0.0-alpha.25 
```

Here is my usual url layout for swagger and redoc:

```
swagger_info = openapi.Info(
    title="something api",
    default_version='v1',
    description="""something API Swagger Definition""",  # noqa
    terms_of_service="https://www.something.com/policies/terms/",
    contact=openapi.Contact(email="contact@something.xyz"),
    license=openapi.License(name="MIT License"),
)

SchemaView = get_schema_view(
    validators=['ssv', 'flex'],
    public=True,
    permission_classes=(permissions.IsAuthenticated,),
)

...

url(r'^swagger(?P<format>\.json|\.yaml)$', SchemaView.without_ui(cache_timeout=None), name='schema-json'),
    url(r'^swagger/$', SchemaView.with_ui('swagger', cache_timeout=None), name='schema-swagger-ui'),
    url(r'^redoc/$', SchemaView.with_ui('redoc', cache_timeout=None), name='schema-redoc'),
```

And my settings:

```
SWAGGER_SETTINGS = {
    'LOGIN_URL': '/session/auth/login',
    'LOGOUT_URL': '/session/auth/logout',
    'DEFAULT_INFO': 'api.urls.swagger_info',
    'SECURITY_DEFINITIONS': {
        'Basic': {
            'type': 'basic'
        },
    },
    'APIS_SORTER': 'alpha',
    'SUPPORTED_SUBMIT_METHODS': ['get', 'post', 'put', 'delete', 'patch'],
    'OPERATIONS_SORTER': 'alpha'
}
REDOC_SETTINGS = {
    'LAZY_RENDERING': True,
}
```

Quick note: if I change permissions to permissions.AllowAny Redoc fails but validation still works.

**Comment by TheSaltman** [comment] 2018-07-03 19:05
I can get swagger to display just fine, but i have restricted security for validation so the validation doesn't work currently. If I change the redoc template to point to the /swagger.json url it seems to work fine.

**Comment by TheSaltman** [comment] 2018-07-03 19:10
swagger validator response with permissions.AllowAny: 

`swagger-validator -s http://127.0.0.1:8000/api/v1/swagger.json
Documents appear to be swagger compliant
Swagger Validation Complete
`

**Comment by axnsan12** [comment] 2018-07-06 12:06
I'm sorry, I don't really follow.


| Perms\Schema url        | /swagger.json | /redoc/?format=openapi |
| ------------- |:-------------:|:-------:|
| permissions.IsAuthenticated      | ReDoc **fail**, validation **success** | ReDoc **fail**, validation **fail** |
| permissions.AllowAny| ReDoc **works**, validation **success** | ReDoc **fail**, validation **success** |

Am I getting this right??

In any case, I would need more than this in order to trace the bug, like something to reproduce it - project code, or at least the generated swagger files.

**Comment by TheSaltman** [comment] 2018-07-23 21:30
Sorry for taking so long to get back to you.

I have tried a couple of things and here is what I have found:

current urls.py
``` python
swagger_info = openapi.Info(
    title="Streisand API",
    default_version='v1',
    description="""Streisand API Swagger Definition""",  # noqa
    terms_of_service="https://www.something.com/policies/terms/",
    contact=openapi.Contact(email="contact@something.xyz"),
    license=openapi.License(name="MIT License"),
)

SchemaView = get_schema_view(
    validators=['ssv', 'flex'],
    public=True,
    permission_classes=(permissions.IsAuthenticated,),
)
```

URLS for redoc and swagger:
``` python
url(r'^swagger(?P<format>.json|.yaml)$', SchemaView.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', SchemaView.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', SchemaView.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    url(r'^cached/swagger(?P<format>.json|.yaml)$', SchemaView.without_ui(cache_timeout=None), name='cschema-json'),
    url(r'^cached/swagger/$', SchemaView.with_ui('swagger', cache_timeout=None), name='cschema-swagger-ui'),
    url(r'^cached/redoc/$', SchemaView.with_ui('redoc', cache_timeout=None), name='cschema-redoc'),
```

swagger urls are fine.

Redoc urls are not.

If I use a base html file with redoc in it: 
[index.zip](https://github.com/axnsan12/drf-yasg/files/2221055/index.zip)
I get no errors. but I am not sure if its the drf-yasg redoc template or what.

Because I still get the error for any redoc url. 
My API is using the IsAdminUser default permissions if that makes a difference. Changing it to IsAuthenticated does not make a difference so I dont think thats it. 
One thing to note over at Redoc:
https://github.com/Rebilly/ReDoc#redoc-options-object


> **lazyRendering** - **Not implemented yet** if set, enables lazy rendering mode in ReDoc. 

Here are my new swagger settings:

``` python


I have attached by swagger json file for you to review.
[swagger.zip](https://github.com/axnsan12/drf-yasg/files/2221113/swagger.zip)

**Comment by TheSaltman** [comment] 2018-08-08 22:09
Just an FYI I was able to spin up a stand-alone redoc instance and npm installed. Redoc had no problem with using swagger.json or swagger.yaml as the specurl but received the exact same error with ?format=openapi. I honestly have no idea how your demo site works using it.

**Comment by axnsan12** [comment] 2018-08-08 22:11
Hmm... which version of redoc did you use?

**Comment by TheSaltman** [comment] 2018-08-08 22:14
Here is my package.json

                                                                                                       
{                                                                                                      
   "name": "redoc",                                                                                    
   "version": "1.0.0",                                                                                 
   "description": "redoc",                                                                             
   "main": "index.js",                                                                                 
   "scripts": {                                                                                        
      "start": "node index.js"                                                                         
   },                                                                                                  
   "license": "MIT",                                                                                   
   "dependencies": {                                                                                   
      "express": "^4.16.3",                                                                            
      "express-status-monitor": "^1.1.5",                                                              
      "jsonformatter": "^0.7.0",                                                                       
      "mobx": "^5.0.3",                                                                                
      "mobx-react": "5.2.3",                                                                           
      "react": "^16.4.2",                                                                              
      "react-dom": "^16.4.2",                                                                          
      "react-dropdown": "1.5.0",                                                                       
      "react-hot-loader": "4.3.4",                                                                     
      "react-tabs": "2.2.2",                                                                           
      "redoc": "^2.0.0-alpha.34",                                                                      
      "styled-components": "3.4.2"                                                                     
   }                                                                                                   
}

**Comment by axnsan12** [comment] 2018-08-08 22:15
And do you get differing swagger JSON content when downloading from ``/swagger.json`` vs ``/redoc/?format=openapi``?

**Comment by TheSaltman** [comment] 2018-08-08 22:17
My index.html 

<!DOCTYPE html>                                                                                        
<html>                                                                                                 
  <head>                                                                                               
    <title>ReDoc</title>                                                                               
                                                                    
    <meta charset="utf-8"/>                                                                            
    <meta name="viewport" content="width=device-width, initial-scale=1">                               
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel$
                                                                                                       
                                                                                                    
    <style>                                                                                            
      body {                                                                                           
        margin: 0;                                                                                     
        padding: 0;                                                                                    
      }                                                                                                
    </style>                                                                                           
  </head>                                                                                              
  <body>                                                                                               
    <redoc spec-url='https://api.something.com/api/v1/swagger.yaml'></redoc>                             
    <script src="/node_modules/redoc/bundles/redoc.standalone.js"> </script>                           
  </body>                                                                                              
</html>

**Comment by axnsan12** [comment] 2018-08-08 23:10
I mean if you go

```
wget http://localhost:8000/swagger.json
wget http://localhost:8000/redoc/?format=openapi
```

Do you get identical files?

**Comment by TheSaltman** [comment] 2018-08-09 00:02
You can’t whet that way it outputs To a file called index.html?format=openapi

**Comment by TheSaltman** [comment] 2018-08-09 00:03
Wget for swagger.json works fine

**Comment by TheSaltman** [comment] 2018-08-09 00:04
I could work on updating your Redoc file to requesting the swagger json file if that would help. Not sure where in your code you do this besides the static folder.

**Comment by axnsan12** [comment] 2018-08-09 00:33
``wget http://localhost:8000/redoc/?format=openapi -O redoc-openapi.json``...?

**Comment by axnsan12** [comment] 2018-08-09 00:36
The latest commit on master should allow you to set the spec url for the bundled ReDoc... can you confirm that it works if you set it to ``/swagger.json`` but not by default?

**Comment by TheSaltman** [comment] 2018-08-09 03:45
Yes that worked perfectly thank you so much!! You are awesome and I love this package and your responsiveness to the repo!!

**Comment by TheSaltman** [comment] 2018-08-09 16:59
Confirmed that the setting fixes it but it doesn’t work if I don’t use the new spec url setting. 
```
Something went wrong...

"https://api.something.com/api/v1/redoc/?format=openapi" is not a valid JSON Schema
Stack trace
https://api.something.com/static/drf-yasg/redoc/redoc.min.js:55:16084
https://api.something.com/static/drf-yasg/redoc/redoc.min.js:73:73711
promiseReactionJob@[native code]

ReDoc Version: 2.0.0-alpha.34 
Commit: fc31145

**Comment by axnsan12** [comment] 2018-08-09 17:29
I'm having a hard time following...

If you set 

```python
REDOC_SETTINGS = {
    'SPEC_URL': 'https://api.something.com/api/v1/swagger.json'
}
```

Does it then magically start working? Or does it have no effect?

Make sure to install drf-yasg from this git repo (because the SPEC_URL change is not yet pushed to pypi).

**Comment by TheSaltman** [comment] 2018-08-10 03:02
Sorry for the confusion. What I am saying is that yes it does work, with the new setting. I was just letting you know that the new setting is the only way to fix it and ?format=openapi continues to break it. 

Thanks for adding that to the code!

**Comment by axnsan12** [comment] 2018-09-09 21:49
Given that I can't reproduce this, and that a workaround has been implemented, I'm closing this as a heisenbug...

**Closed by axnsan12** 2018-09-09 21:49 UTC
Labels: bug

**Comment by markddavidoff** [comment] 2018-10-25 21:18
@axnsan12 @TheSaltman I'm getting this same issue in `1.11.0`. If I set the spec url setting like you posted above (changint the url to point to my ` url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json')` api):
> ```python
> REDOC_SETTINGS = {
>     'SPEC_URL': 'https://api.something.com/api/v1/swagger.json'
> }
> ```

then redoc works fine. Without that and a setup like the one above and the one in the docs I get:
![image](https://user-images.githubusercontent.com/1360543/47530840-9a2e8480-d860-11e8-94e6-ea1ded887504.png)

This is an issue as i want to have multiple docs endpoints and seeing as the redoc setting is global, this workaround isn't enough.

**Comment by axnsan12** [comment] 2018-10-25 21:34
That's still not enough info to work on, I'd need a full project that reproduces this, or some output to compare from the two different URLs...

**Comment by markddavidoff** [comment] 2018-10-25 22:42
What output do you need? the `wget http://localhost:8000/redoc/?format=openapi` returns the rendered html. is that what you want? It seems the issue is with whatever logic resolves `?format=openapi` into the swagger spec url. That works for the swagger endpoint but not the redoc one. If you can point me at where the redoc renderer is supposed to get the swagger schema url, I can step through and see whats going on.

**Comment by BrianMarquez3** [comment] 2022-06-10 14:47
![image](https://user-images.githubusercontent.com/11839204/173091165-52cbd314-0547-480b-a1f2-8cbfd2fcc40a.png)

For the first time I face a problem like this, I can't find a solution
