### ISSUE TITLE
Update to `requirements/base.txt` did not make the 1.16.1 release

### ISSUE THREAD

**Issue by MichaelKim0407** [axnsan12/drf-yasg#433] opened 2019-08-05 17:49 UTC
Please re-release the package; I just downloaded 1.16.1 from pypi and this is the content of `requirements/base.txt`:

```
coreapi>=2.3.3
coreschema>=0.0.4
ruamel.yaml>=0.15.34
inflection>=0.3.1
six>=1.10.0
uritemplate>=3.0.0

djangorestframework>=3.8
Django>=1.11.7
```

apparently the changes did not make it to the tarball.

**Comment by axnsan12** [comment] 2019-09-29 15:45
Duplicate of #412

**Closed by axnsan12** 2019-09-29 15:45 UTC
