### ISSUE TITLE
NotImplementedError(".get_schema() must be implemented in subclasses.")

### ISSUE THREAD

**Issue by jackson1992121** [axnsan12/drf-yasg#656] opened 2020-10-13 20:10 UTC
Now I'm using Django 3.1.2 and Djangorestframework 3.11.0. And when I want to visit "localhost:8000/redoc" the above error occurs.
I don't know what to do.
Please help me.
![スクリーンショット 2020-10-14 041136](https://user-images.githubusercontent.com/50630029/95910944-680ee800-0dd3-11eb-91d7-5cf9240405e6.png)

**Comment by my-call** [comment] 2020-10-15 06:08
me too...
help me

**Comment by my-call** [comment] 2020-10-15 06:35
hello

This library is not being updated.

use this library 

https://github.com/JoelLefkowitz/drf-yasg

**Comment by betoecd** [comment] 2020-10-19 12:57
Pin django rest framework version
`djangorestframework==3.11`

Remove `DEFAULT_GENERATOR_CLASS` in `settings.py`

**Comment by axnsan12** [comment] 2020-10-25 22:23
I think this was a bug in an older drf patch version. In any case it should be fixed in 1.20.0, please reopen provide a more complete reproduction if it's still an issue for you.

**Closed by axnsan12** 2020-10-25 22:23 UTC

**Comment by aymaneMx** [comment] 2020-11-03 16:09
@axnsan12  I'm using `drf-yasg = "==1.20.0"` and the issue still persist, 

also:
```
Django = "==3.1.2"
djangorestframework = "==3.12.1"
django-rest-swagger = "==2.2.0"
```

```python
schema_view = get_schema_view(
    openapi.Info(title="API Documentation", default_version="v1"),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
]
```

**Comment by aymaneMx** [comment] 2020-11-03 16:12
removing `DEFAULT_GENERATOR_CLASS` in `settings.py` works for me. 
thanks @betoecd
