### ISSUE TITLE
ImportError: cannot import name 'URLPattern' from 'rest_framework.compat'

### ISSUE THREAD

**Issue by miyagin15** [axnsan12/drf-yasg#649] opened 2020-10-04 04:16 UTC
Hi 
I use drf-yasg and it is very useful tool !!!
In generators.py of drf-yasg, it uses following now.
https://github.com/axnsan12/drf-yasg/blob/9ccf24c27ad46db4f566170553d49d687b6d21d6/src/drf_yasg/generators.py#L11

However, I think rest_framework.compat don't use URLPattern now. 
https://github.com/encode/django-rest-framework/commit/bb795674f86828fc5f15d6d61501cc781811e053#diff-ce493f71b3679e91b72126c168670399

So I think drf-yasg can't import URLPattern and raise Exception.
```
ImportError: cannot import name 'URLPattern' from 'rest_framework.compat' (/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/python3.7/site-packages/rest_framework/compat.py)
```

Although I don't know the accurate method to resolve it, why don't you add the following code in generators.py
```
    from django.urls import (  # noqa
        URLPattern,
        URLResolver,
    )
```

**Comment by cristianocca** [comment] 2020-10-06 02:20
Same issue here after upgrading to DRF 3.12.1

**Comment by ixna** [comment] 2020-10-06 04:25
issue on drf, solved by revert to drf 3.11.2

**Comment by johnthagen** [comment] 2020-10-06 12:30
Duplicate of #641

**Comment by snowman2** [comment] 2020-10-07 19:41
Experiencing same issue here.

**Comment by johnthagen** [comment] 2020-10-07 20:43
See https://github.com/axnsan12/drf-yasg/issues/641#issuecomment-704327697 as a possible fork that is getting off the ground.

**Comment by axnsan12** [comment] 2020-10-25 19:12
Fixed now in master, thanks for the report.

**Closed by axnsan12** 2020-10-25 19:12 UTC
