### ISSUE TITLE
read_only fields are ignored in example value but NOT in MODEL

### ISSUE THREAD

**Issue by zzinny** [axnsan12/drf-yasg#467] opened 2019-10-02 02:47 UTC
As shown below, my read_only field `created_at` is ignored in `Example Value` option, but not in `Model` option.
![image](https://user-images.githubusercontent.com/24687378/66014110-8f687f00-e508-11e9-9a5a-4c530f80b0e8.png)

![image](https://user-images.githubusercontent.com/24687378/66014103-87a8da80-e508-11e9-97bc-c81cc151c13e.png)

I confirmed that this problem was fixed in #261 and I'm using the fixed version of `1.15.0`, but the problem remains.

**Comment by axnsan12** [comment] 2019-10-02 04:47
I'm not really sure what the problem is here. The screenshot clearly shows the field marked as readOnly.

**Closed by axnsan12** 2019-10-02 04:47 UTC

**Comment by zzinny** [comment] 2019-10-02 05:15
> I'm not really sure what the problem is here. The screenshot clearly shows the field marked as readOnly.

Right. I misunderstood that read_only fields should not be shown in `Model`. Thanks.
